---
title: "Untitled"
author: "Robert Hickman"
date: "7 August 2018"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(dplyr)
library(magrittr)
library(ggplot2)
library(ggparliament)
library(tidyr)
```

```{r}
#get the data for the last election
uk <- election_data %>%
  filter(country == "UK") %>%
  filter(year == 2017) %>%
  #parl_data it out
  parliament_data(election_data = .,
                  party_seats = .$seats,
                  group = .$government,
                  parl_rows = 12,
                  type = "opposing_benches")

#add to function to calculate thresholds for opposing benches
maj_threshold <- (ceiling(nrow(plot$data) / 2) / (length(unique(plot$data$x)) / 2)) + 0.5

#plot it
plot <- ggplot(uk, aes(x, y, colour = party_short)) +
  geom_parliament_seats() +
  geom_highlight_government(government == 1) +
  scale_colour_manual(values = uk$colour, 
                      limits = uk$party_short) + 
  geom_hline(yintercept = maj_threshold, linetype = "dashed") +
  theme_ggparliament()

```

```{r}
#HANSARD PACKAGE INTEGRATION


```

