---
title: "How to facet parliaments by year or house"
author: "Zoe Meers"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

source("../R/parliament_data.R")
source("../R/helper_funcs.R")
source("../R/draw_majoritythreshold.R")
source("../R/draw_legislaturelabels.R")
library(tidyverse)

```




If you want to facet a parliament, you can use a split-apply-combine strategy in a `dplyr` chain.

## Steps
You must:

1) split by year
2) apply the coordinates for each party
3) combine the rows into one large data frame.

A few examples are as follows:

### American Congress from 2010 onwards
```{r}
usa <- election_data %>%
  filter(country == "USA" &
    house == "Representatives")  %>% 
  split(.$year) %>% # split
  map(~parliament_data(election_data = ., # apply
  total_seats = sum(.$seats),
  party_seats = .$seats,
  parl_rows = 8,
  type = "semicircle")) %>%
  bind_rows() # combine
```

```{r, fig.width=12, fig.height=4}
us <- ggplot(usa, aes(x, y, colour = party_short, type = "semicircle")) +
  geom_parliament_seats() + 
  geom_highlight_government(government == 1) + 
  labs(colour = NULL, 
       title = "American Congress",
       subtitle = "The party that has control of US Congress is encircled in black.") +
  theme_void() +
  scale_colour_manual(values = usa$colour, 
                      limits = usa$party_short) + 
  theme(legend.position = 'bottom') + 
  facet_grid(~year, scales = 'free') 

us
```


### Facet Australian Parliament by House
```{r}
australia <- election_data %>%
  filter(country == "Australia" &
    year == "2016")  %>% 
  split(.$house) %>% # split
  map(~parliament_data(election_data = ., # apply
  total_seats = sum(.$seats),
  party_seats = .$seats,
  parl_rows = 4,
  type = "horseshoe")) %>%
  bind_rows() # combine
```

```{r,fig.width=8, fig.height=5}
au <- ggplot(australia, aes(x, y, colour=party_short, type = "horseshoe")) +
  geom_parliament_seats() + 
  geom_highlight_government(government == 1) + 
  labs(colour = NULL, 
       title = "Australian Parliament",
       subtitle = "Government encircled in black.") +
  scale_colour_manual(values = australia$colour, 
                      limits = australia$party_short) + 
  theme_void() +
  theme(legend.position = 'bottom') + 
  facet_grid(~house, scales = 'free')

au

```

### Facet UK Parliament

```{r}
uk_left<- election_data %>%
  filter(country == "UK" & 
           government == 0)  %>%
  split(.$year) %>%
  map(~parliament_data(election_data = .,
  total_seats = sum(.$seats),
  party_seats = .$seats,
  parl_rows = 12,
  type = "opposing_benches")) %>%
  bind_rows()

uk_right<-election_data %>%
  filter(country == "UK" & 
           government == 1)  %>%
  split(.$year) %>%
  map(~parliament_data(election_data = .,
  total_seats = sum(.$seats),
  party_seats = .$seats,
  parl_rows = 12,
  type = "opposing_benches")) %>%
  bind_rows()


```


```{r, fig.height=10, fig.width=6}
right_all <- ggplot(uk_right, aes(x, y, colour = party_short, type = "opposing_benches")) +
  geom_parliament_seats() + 
  geom_highlight_government(government == 1) + 
  theme_void() +
  labs(colour = NULL) +
  scale_colour_manual(values = uk_right$colour, 
                      limits = uk_right$party_short) +
  theme(legend.position = 'right')+
  facet_wrap(~year, ncol = 1)


left_all <- ggplot(uk_left, aes(x, y, colour = party_short, type = "opposing_benches")) +
  geom_parliament_seats() + 
  theme_void() +
  labs(colour = NULL, 
       title = "UK parliament",
       subtitle="Government encircled in black.") +
  scale_colour_manual(values = uk_left$colour, 
                      limits = uk_left$party_short) +
  theme(legend.position = 'left') +
  facet_wrap(~year, ncol = 1)

uk_parliament_10_15_17 <- combine_opposingbenches(left = left_all, 
                                                  right = right_all)
uk_parliament_10_15_17
```




