---
title: "How to highlight government or party in control of the legislature"
author: "Zoe Meers"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

source("../R/parliament_data.R")
source("../R/helper_funcs.R")
source("../R/draw_majorityline.R")
source("../R/draw_legislaturelabels.R")
library(tidyverse)
election_data <- readRDS(file="../data/election_data.rda")

```


# Labels
To add labels for political parties and the total number of MPs in the centre of the plot, you can add `draw_legislaturelabels()` to the ggplot2 object.
You must define the `total_parliamentary_seats` and the type of parliament (semicircle, horseshoe, etc.)

```{r}

us_congress <- election_data %>%
  filter(country == "USA" &
    year == 2016 &
    house == "Representatives")

us_congress1 <- parliament_data(election_data = us_congress,
  type = "semicircle",
  total_seats = sum(us_congress$seats),
  parl_rows = 10,
  party_names = us_congress$party_short,
  party_seats = us_congress$seats)

ggplot(us_congress1, aes(x, 
                   y, 
                   colour = party_short)) +
  geom_parliament_seats() + 
  geom_highlight_government(government == 1) + 
  draw_majoritythreshold(n = 218,
                         type = "semicircle") + 
  draw_legislaturelabels(total_parliamentary_seats = 435,
                         type = 'semicircle') + 
  theme_void() +
  theme(legend.position = 'none') + 
  labs(title = "2016 American Congress",
       subtitle = "Party that controls the chamber is highlighted in black.") +
  scale_colour_manual(values = us_congress1$colour, 
                      limits = us_congress1$party_short) 

```
